title: ElectroCRUD 2 (beta)
description: Simple solution to manage your database that not involves writing code or installs web-based solutions.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
